const products = [
  {
    id: 1,
    name: 'Banana',
    href: '#',
    imageSrc: '/src/assets/products/banana.png',
    imageAlt: 'Banana',
    price: 183.0,
    category: 'fruits',
    countInStock: 10,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 2,
    name: 'Avocado',
    href: '#',
    imageSrc: '/src/assets/products/avocado.png',
    imageAlt: 'Avocado',
    price: 378.0,
    category: 'fruits',
    countInStock: 5,
    rating: 5,
    numReviews: 7,
  },
  {
    id: 3,
    name: 'Beef Tenderloin',
    href: '#',
    imageSrc: '/src/assets/products/beef-tenderloin.jpg',
    imageAlt: 'Beef Tenderloin',
    price: 500.0,
    category: 'meat',
    countInStock: 8,
    rating: 4.5,
    numReviews: 10,
  },
  {
    id: 4,
    name: 'Pork Loin',
    href: '#',
    imageSrc: '/src/assets/products/pork-loin.jpg',
    imageAlt: 'Pork Loin',
    price: 480.0,
    category: 'meat',
    countInStock: 6,
    rating: 3.5,
    numReviews: 4,
  },
  {
    id: 5,
    name: 'Carrots',
    href: '#',
    imageSrc: '/src/assets/products/carrots.png',
    imageAlt: 'Carrots',
    price: 289.0,
    category: 'vegetables',
    countInStock: 15,
    rating: 4.5,
    numReviews: 12,
  },
  {
    id: 6,
    name: 'Eggplant',
    href: '#',
    imageSrc: '/src/assets/products/eggplant.png',
    imageAlt: 'Eggplant',
    price: 215.0,
    category: 'vegetables',
    countInStock: 12,
    rating: 4.5,
    numReviews: 7,
  },
  {
    id: 7,
    name: 'Tuna',
    href: '#',
    imageSrc: '/src/assets/products/tuna.png',
    imageAlt: 'Tuna',
    price: 679.0,
    category: 'fish',
    countInStock: 4,
    rating: 5,
    numReviews: 12,
  },
  {
    id: 8,
    name: 'Shrimp',
    href: '#',
    imageSrc: '/src/assets/products/shrimp.jpg',
    imageAlt: 'Shrimp',
    price: 289.0,
    category: 'fish',
    countInStock: 10,
    rating: 4,
    numReviews: 8,
  },
]

export default products
